// Mocks generated by Mockito 5.0.16 from annotations
// in tv/test/helpers/test_helper.dart.
// Do not manually edit this file.

import 'dart:async' as _i7;
import 'dart:convert' as _i17;
import 'dart:typed_data' as _i18;

import 'package:core/core.dart' as _i6;
import 'package:dartz/dartz.dart' as _i4;
import 'package:http/http.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:sqflite/sqflite.dart' as _i8;
import 'package:tv/data/datasources/tv_local_data_source.dart' as _i9;
import 'package:tv/data/datasources/tv_remote_data_source.dart' as _i11;
import 'package:tv/data/models/tv_season_detail_model.dart' as _i3;
import 'package:tv/data/models/tv_series_detail_model.dart' as _i2;
import 'package:tv/data/models/tv_series_model.dart' as _i12;
import 'package:tv/data/models/tv_series_table.dart' as _i10;
import 'package:tv/domain/entities/tv_season_detail.dart' as _i16;
import 'package:tv/domain/entities/tv_series.dart' as _i14;
import 'package:tv/domain/entities/tv_series_detail.dart' as _i15;
import 'package:tv/domain/repositories/tv_series_repository.dart' as _i13;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeTvSeriesDetailResponse_0 extends _i1.Fake
    implements _i2.TvSeriesDetailResponse {}

class _FakeTvSeasonDetailResponse_1 extends _i1.Fake
    implements _i3.TvSeasonDetailResponse {}

class _FakeEither_2<L, R> extends _i1.Fake implements _i4.Either<L, R> {}

class _FakeResponse_3 extends _i1.Fake implements _i5.Response {}

class _FakeStreamedResponse_4 extends _i1.Fake implements _i5.StreamedResponse {
}

/// A class which mocks [DatabaseHelper].
///
/// See the documentation for Mockito's code generation for more information.
class MockDatabaseHelper extends _i1.Mock implements _i6.DatabaseHelper {
  MockDatabaseHelper() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i8.Database?> get database => (super.noSuchMethod(
      Invocation.getter(#database),
      returnValue: Future<_i8.Database?>.value()) as _i7.Future<_i8.Database?>);
  @override
  _i7.Future<int> insertWatchlist(dynamic item) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [item]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<int> removeWatchlist(dynamic item) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [item]),
          returnValue: Future<int>.value(0)) as _i7.Future<int>);
  @override
  _i7.Future<Map<String, dynamic>?> getItemById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getItemById, [id]),
              returnValue: Future<Map<String, dynamic>?>.value())
          as _i7.Future<Map<String, dynamic>?>);
  @override
  _i7.Future<List<Map<String, dynamic>>> getWatchlistItem() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistItem, []),
              returnValue: Future<List<Map<String, dynamic>>>.value(
                  <Map<String, dynamic>>[]))
          as _i7.Future<List<Map<String, dynamic>>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TvSeriesLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesLocalDataSource extends _i1.Mock
    implements _i9.TvSeriesLocalDataSource {
  MockTvSeriesLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<String> insertWatchlist(_i10.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#insertWatchlist, [tvSeries]),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<String> removeWatchlist(_i10.TvSeriesTable? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tvSeries]),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<_i10.TvSeriesTable?> getTvSeriesById(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvSeriesById, [id]),
              returnValue: Future<_i10.TvSeriesTable?>.value())
          as _i7.Future<_i10.TvSeriesTable?>);
  @override
  _i7.Future<List<_i10.TvSeriesTable>> getWatchlistTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getWatchlistTvSeries, []),
          returnValue: Future<List<_i10.TvSeriesTable>>.value(
              <_i10.TvSeriesTable>[])) as _i7.Future<List<_i10.TvSeriesTable>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TvSeriesRemoteDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRemoteDataSource extends _i1.Mock
    implements _i11.TvSeriesRemoteDataSource {
  MockTvSeriesRemoteDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i12.TvSeriesModel>> getNowPlayingTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getNowPlayingTvSeries, []),
          returnValue: Future<List<_i12.TvSeriesModel>>.value(
              <_i12.TvSeriesModel>[])) as _i7.Future<List<_i12.TvSeriesModel>>);
  @override
  _i7.Future<List<_i12.TvSeriesModel>> getPopularTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getPopularTvSeries, []),
          returnValue: Future<List<_i12.TvSeriesModel>>.value(
              <_i12.TvSeriesModel>[])) as _i7.Future<List<_i12.TvSeriesModel>>);
  @override
  _i7.Future<List<_i12.TvSeriesModel>> getTopRatedTvSeries() =>
      (super.noSuchMethod(Invocation.method(#getTopRatedTvSeries, []),
          returnValue: Future<List<_i12.TvSeriesModel>>.value(
              <_i12.TvSeriesModel>[])) as _i7.Future<List<_i12.TvSeriesModel>>);
  @override
  _i7.Future<_i2.TvSeriesDetailResponse> getTvSeriesDetail(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvSeriesDetail, [id]),
              returnValue: Future<_i2.TvSeriesDetailResponse>.value(
                  _FakeTvSeriesDetailResponse_0()))
          as _i7.Future<_i2.TvSeriesDetailResponse>);
  @override
  _i7.Future<List<_i12.TvSeriesModel>> getTvSeriesRecommendations(int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvSeriesRecommendations, [id]),
          returnValue: Future<List<_i12.TvSeriesModel>>.value(
              <_i12.TvSeriesModel>[])) as _i7.Future<List<_i12.TvSeriesModel>>);
  @override
  _i7.Future<_i3.TvSeasonDetailResponse> getTvSeriesSeasonDetail(
          int? tvId, int? seasonNumber) =>
      (super.noSuchMethod(
              Invocation.method(#getTvSeriesSeasonDetail, [tvId, seasonNumber]),
              returnValue: Future<_i3.TvSeasonDetailResponse>.value(
                  _FakeTvSeasonDetailResponse_1()))
          as _i7.Future<_i3.TvSeasonDetailResponse>);
  @override
  _i7.Future<List<_i12.TvSeriesModel>> searchTvSeries(String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvSeries, [query]),
          returnValue: Future<List<_i12.TvSeriesModel>>.value(
              <_i12.TvSeriesModel>[])) as _i7.Future<List<_i12.TvSeriesModel>>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [TvSeriesRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTvSeriesRepository extends _i1.Mock
    implements _i13.TvSeriesRepository {
  MockTvSeriesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>
      getNowPlayingTvSeries() => (super.noSuchMethod(
              Invocation.method(#getNowPlayingTvSeries, []),
              returnValue:
                  Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>.value(
                      _FakeEither_2<_i6.Failure, List<_i14.TvSeries>>()))
          as _i7.Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>);
  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>
      getPopularTvSeries() => (super.noSuchMethod(
              Invocation.method(#getPopularTvSeries, []),
              returnValue:
                  Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>.value(
                      _FakeEither_2<_i6.Failure, List<_i14.TvSeries>>()))
          as _i7.Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>);
  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>
      getTopRatedTvSeries() => (super.noSuchMethod(
              Invocation.method(#getTopRatedTvSeries, []),
              returnValue:
                  Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>.value(
                      _FakeEither_2<_i6.Failure, List<_i14.TvSeries>>()))
          as _i7.Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>);
  @override
  _i7.Future<_i4.Either<_i6.Failure, _i15.TvSeriesDetail>> getTvSeriesDetail(
          int? id) =>
      (super.noSuchMethod(Invocation.method(#getTvSeriesDetail, [id]),
              returnValue:
                  Future<_i4.Either<_i6.Failure, _i15.TvSeriesDetail>>.value(
                      _FakeEither_2<_i6.Failure, _i15.TvSeriesDetail>()))
          as _i7.Future<_i4.Either<_i6.Failure, _i15.TvSeriesDetail>>);
  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>
      getTvSeriesRecommendations(int? id) => (super.noSuchMethod(
              Invocation.method(#getTvSeriesRecommendations, [id]),
              returnValue:
                  Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>.value(
                      _FakeEither_2<_i6.Failure, List<_i14.TvSeries>>()))
          as _i7.Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>);
  @override
  _i7.Future<_i4.Either<_i6.Failure, _i16.TvSeriesSeasonDetail>>
      getTvSeriesSeasonDetail(int? tvId, int? seasonNumber) => (super.noSuchMethod(
              Invocation.method(#getTvSeriesSeasonDetail, [tvId, seasonNumber]),
              returnValue: Future<
                      _i4.Either<_i6.Failure, _i16.TvSeriesSeasonDetail>>.value(
                  _FakeEither_2<_i6.Failure, _i16.TvSeriesSeasonDetail>()))
          as _i7.Future<_i4.Either<_i6.Failure, _i16.TvSeriesSeasonDetail>>);
  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>> searchTvSeries(
          String? query) =>
      (super.noSuchMethod(Invocation.method(#searchTvSeries, [query]),
              returnValue:
                  Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>.value(
                      _FakeEither_2<_i6.Failure, List<_i14.TvSeries>>()))
          as _i7.Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>);
  @override
  _i7.Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>
      getWatchlistTvSeries() => (super.noSuchMethod(
              Invocation.method(#getWatchlistTvSeries, []),
              returnValue:
                  Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>.value(
                      _FakeEither_2<_i6.Failure, List<_i14.TvSeries>>()))
          as _i7.Future<_i4.Either<_i6.Failure, List<_i14.TvSeries>>>);
  @override
  _i7.Future<_i4.Either<_i6.Failure, String>> saveWatchlist(
          _i15.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#saveWatchlist, [tvSeries]),
              returnValue: Future<_i4.Either<_i6.Failure, String>>.value(
                  _FakeEither_2<_i6.Failure, String>()))
          as _i7.Future<_i4.Either<_i6.Failure, String>>);
  @override
  _i7.Future<_i4.Either<_i6.Failure, String>> removeWatchlist(
          _i15.TvSeriesDetail? tvSeries) =>
      (super.noSuchMethod(Invocation.method(#removeWatchlist, [tvSeries]),
              returnValue: Future<_i4.Either<_i6.Failure, String>>.value(
                  _FakeEither_2<_i6.Failure, String>()))
          as _i7.Future<_i4.Either<_i6.Failure, String>>);
  @override
  _i7.Future<bool> isAddedToWatchlist(int? id) =>
      (super.noSuchMethod(Invocation.method(#isAddedToWatchlist, [id]),
          returnValue: Future<bool>.value(false)) as _i7.Future<bool>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [Client].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i5.Client {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.Response> head(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#head, [url], {#headers: headers}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> get(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#get, [url], {#headers: headers}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> post(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i17.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#post, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> put(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i17.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#put, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> patch(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i17.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#patch, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<_i5.Response> delete(Uri? url,
          {Map<String, String>? headers,
          Object? body,
          _i17.Encoding? encoding}) =>
      (super.noSuchMethod(
              Invocation.method(#delete, [url],
                  {#headers: headers, #body: body, #encoding: encoding}),
              returnValue: Future<_i5.Response>.value(_FakeResponse_3()))
          as _i7.Future<_i5.Response>);
  @override
  _i7.Future<String> read(Uri? url, {Map<String, String>? headers}) =>
      (super.noSuchMethod(Invocation.method(#read, [url], {#headers: headers}),
          returnValue: Future<String>.value('')) as _i7.Future<String>);
  @override
  _i7.Future<_i18.Uint8List> readBytes(Uri? url,
          {Map<String, String>? headers}) =>
      (super.noSuchMethod(
              Invocation.method(#readBytes, [url], {#headers: headers}),
              returnValue: Future<_i18.Uint8List>.value(_i18.Uint8List(0)))
          as _i7.Future<_i18.Uint8List>);
  @override
  _i7.Future<_i5.StreamedResponse> send(_i5.BaseRequest? request) =>
      (super.noSuchMethod(Invocation.method(#send, [request]),
              returnValue:
                  Future<_i5.StreamedResponse>.value(_FakeStreamedResponse_4()))
          as _i7.Future<_i5.StreamedResponse>);
  @override
  void close() => super.noSuchMethod(Invocation.method(#close, []),
      returnValueForMissingStub: null);
  @override
  String toString() => super.toString();
}
